mod
    -> "mod" path statement*;
    ;

path
    -> IDENT ("." IDENT)*
    ;

statement
    -> function
    |  ext
    |  use
    ;

function
    -> type IDENT parameters compound
    ;

type
    -> IDENT ("*" | "[]")*
    ;

parameters
    -> "(" (parameter ("," parameter)*)? ")"
    ;

parameter
    -> type IDENT
    |  IDENT "..."
    ;

compound
    -> "{" compound_statement "}"
    ;

compound_statement
    -> ret
    |  identifier_statement
    ;

ret
    -> "ret" expr? ";"
    ;

expr
    -> term (("+" | "-" | "&&" | "||") term)*
    ;

term
    -> factor (("*" | "/" | "==" | "!=") factor)*
    ;

factor
    -> INT
    |  BOOL
    |  STRING
    |  identifier_expr
    |  "(" expr ")"
    ;

identifier_expr
    -> call
    |  access
    |  IDENT
    ;

ext
    -> "ext" type IDENT parameters ";"
    ;

identifier_statement
    -> call ";"
    ;

call
    -> path arguments
    ;

arguments
    -> "(" (expr ("," expr)*)? ")"
    ;

use
    -> "use" path ";"
    ;

access
    -> IDENT "." identifier_expr
    ;
