IDENT         ::= [a-zA-Z_$][a-zA-Z0-9_$]*
INT           ::= 0x[0-9a-fA-F][0-9a-fA-F_]* | [0-9][0-9_]*
REAL          ::= [0-9][0-9_]*\.[0-9][0-9_]*
STRING        ::= "([^"\\]|\\.)*"
CHAR          ::= '([^'\\]|\\.)'
LINE_COMMENT  ::= //[^\n]*\n
BLOCK_COMMENT ::= /\*.*?\*/

KW_MOD      ::= mod
KW_RET      ::= ret
KW_EXT      ::= ext
KW_USE      ::= use
KW_IF       ::= if
KW_ELSE     ::= else
KW_TYPE     ::= type
KW_NEW      ::= new
KW_WHILE    ::= while
KW_BASE     ::= base
KW_AS       ::= as
KW_SWITCH   ::= switch
KW_CASE     ::= case
KW_DEFAULT  ::= default
KW_BREAK    ::= break
KW_TRAP     ::= trap
KW_CONST    ::= conts
KW_TRY      ::= try
KW_CATCH    ::= catch
KW_ERR      ::= err
TRUE        ::= true
FALSE       ::= false
NULL        ::= null

SEMI        ::= ;
LPAREN      ::= (
RPAREN      ::= )
LBRACKET    ::= [
RBRACKET    ::= ]
LBRACE      ::= {
RBRACE      ::= }
LANGLE      ::= <
RANGLE      ::= >
PLUS        ::= +
MINUS       ::= -
ASTERISK    ::= *
SLASH       ::= /
EQUALS      ::= =
PERIOD      ::= .
COMMA       ::= ,
AMP         ::= &
BANG        ::= !
COLON       ::= :
PIPE        ::= |
CARET       ::= ^
TILDA       ::= ~
ELLIPSE     ::= ...
OR          ::= ||
AND         ::= &&
IS_EQUAL    ::= ==
NOT_EQUAL   ::= !=
GTE         ::= >=
LTE         ::= <=
SHL         ::= <<
SHR         ::= >>

module
    ::= KW_MOD path SEMI top_level_statement*

top_level_statement
    ::= function
	|   ext_decl
	|   use_decl
	|   struct_decl
	|   base_decl
	|   const_decl

path
    ::= IDENT (PERIOD IDENT)*

function
    ::= function_signature compound

function_signature
    ::= type IDENT parameters

parameters
    ::= LPAREN (parameter (COMMA parameter)*)? RPAREN

parameter
    ::= type? IDENT ELLIPSE?

ext_decl
    ::= KW_EXT function_signature SEMI

base_decl
    ::= KW_BASE IDENT LBRACE base_function* RBRACE

base_function
    ::= function_signature SEMI

type
    ::= path (ASTERISK | LBRACKET expr? RBRACKET)*

struct_decl
    ::= KW_TYPE IDENT fields (COLON path)? SEMI

fields
    ::= LPAREN (field (COMMA field)*)? RPAREN

field
    ::= type IDENT

use_decl
    ::= KW_USE path SEMI

compound
    ::= LBRACE compound_statement* RBRACE

compound_statement
    ::= ret_stmt
    |   identifier_statement
	|   if_stmt
	|   assign_or_expr_statement
    |   while_stmt
    |   switch_stmt
    |   break_stmt
    |   trap_stmt
    |   try_stmt
    |   err_stmt

ret_stmt
    ::= KW_RET expr? SEMI

break_stmt
    ::= KW_BREAK SEMI

trap_stmt
    ::= KW_TRAP SEMI

identifier_statement
    ::= call_statement
	|   variable
	|   assign_or_expr_statement

call_statement
    ::= call SEMI

variable
    ::= type IDENT (EQUALS expr)? SEMI

assign_or_expr_statement
    ::= expr (EQUALS expr)? SEMI

if_stmt
    ::= KW_IF LPAREN expr RPAREN compound (KW_ELSE (if_stmt | compound))?

while_stmt
    ::= KW_WHILE LPAREN expr RPAREN compound

switch_stmt
    ::= KW_SWITCH LPAREN expr RPAREN LBRACE switch_case* RBRACE

switch_case
    ::= case_clause
	|   default_clause

case_clause
    ::= KW_CASE expr COLON compound_statement*

default_clause
    ::= KW_DEFAULT COLON compound_statement*

expr
    ::= binary_expr

binary_expr
    ::= factor (binary_operator factor)*

binary_operator
    ::= OR
	|   AND
	|   IS_EQUAL
	|   NOT_EQUAL
	|   GTE
	|   LTE
	|   SHL
	|   SHR
    |   LANGLE
	|   RANGLE
	|   PLUS
	|   MINUS
	|   ASTERISK
	|   SLASH
	|   AMP
	|   PIPE
	|   CARET

factor
    ::= primary suffix_op? cast_op*

primary
    ::= INT
    |   bool_literal
    |   STRING
    |   identifier_expr
    |   LPAREN expr RPAREN
    |   unary_expr
    |   init_expr
    |   null_expr
    |   reference_expr
    |   dereference_expr
    |   REAL
    |   CHAR
    |   array_expr

bool_literal
    ::= TRUE | FALSE

identifier_expr
    ::= call | access | IDENT

call
    ::= path arguments

arguments
    ::= LPAREN (expr (COMMA expr)*)? RPAREN

access
    ::= IDENT PERIOD identifier_expr

unary_expr
    ::= (TILDA | BANG | PLUS | MINUS) expr

init_expr
    ::= KW_NEW path arguments

null_expr
    ::= NULL

reference_expr
    ::= AMP expr

dereference_expr
    ::= ASTERISK factor

array_expr
    ::= LBRACKET (expr (COMMA expr)*)? RBRACKET

suffix_op
    ::= index_or_slice* repeated_op?

index_or_slice
    ::= LBRACKET expr (COLON expr)? RBRACKET

repeated_op
    ::= (PLUS PLUS) | (MINUS MINUS) | (BANG BANG)

cast_op
    ::= KW_AS type

const_decl
    ::= KW_CONST type IDENT EQUALS expr SEMI

try_stmt
    ::= KW_TRY compound KW_CATCH LPAREN parameter RPAREN compound

err_stmt
    ::= KW_ERR path arguments SEMI
